services:
  web-app:
    build: 
      context: .
    ports:
      - '8001:8001'
    volumes:
      - ./service:/service

    environment:
      - DB_HOST=database
      - DB_NAME=django-app
      - DB_USER=django-user
      - DB_PASS=django-password

    command: >
      sh -c 'python3 manage.py runserver 0.0.0.0:8001'

    depends_on:
      - database


  database:
    image: postgres:14.6
    environment:
      - POSTGRES_DB=django-app
      - POSTGRES_USER=django-user
      - POSTGRES_PASSWORD=django-password

  redis:
    image: redis:7.0.5
    hostname: redis

  worker:
    build: 
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./service:/service
    links:
      - redis
    depends_on:
      - redis
      - database
    environment:
      - DB_HOST=database
      - DB_NAME=django-app
      - DB_USER=django-user
      - DB_PASS=django-password

  worker2:
    build: 
      context: .
    hostname: worker2
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./service:/service
    links:
      - redis
    depends_on:
      - redis
      - database
    environment:
      - DB_HOST=database
      - DB_NAME=django-app
      - DB_USER=django-user
      - DB_PASS=django-password

  flower:
    build: 
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./service:/service
    links:
      - redis
    depends_on:
      - redis
    ports:
      - '5555:5555'